# Generated by Django 3.2.13 on 2022-12-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20221209_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idiomas',
            options={'verbose_name_plural': 'idiomas'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='apeliido',
            new_name='apellido',
        ),
    ]
