# Generated by Django 3.2.13 on 2022-12-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20221210_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'autor'},
        ),
        migrations.AlterField(
            model_name='autor',
            name='agno_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='año nacimiento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fallecimiento'),
        ),
    ]
